### ISSUE TITLE
Add a blank line before and after a list of books

### ISSUE THREAD

**Issue by Di30an** [Di30an/readinglist#8]
In the ui.py show_books function, print a blank line before and after the list of books, or the 'no books' message.

**Comment by cgisala** [comment]
Fixed the issue by adding two print blank line function on lines 28 and 32 of ui.py

**Comment by cgisala** [comment]
Added a new line escape sequence at the end of the message on line 34.

**Comment by cgisala** [comment]
Added print statements with newline escape sequence and modified the commit messages.
